### ISSUE TITLE
how about gcp version

### ISSUE THREAD

**Issue by Wolke** [Vadorequest/serverless-with-next5-boilerplate#2]
as title

**Comment by Vadorequest** [comment]
@Wolke I haven't tried to run against GCP so far, the lack of SLS plugins, especially development-friendly plugin (like serverless-offline) made me switch to AWS in my early Serverless days.

I believe removing the use of aws-only plugins would allow to switch to GCP provider, but that's not trivial and I won't do it myself since I'm not gonna use it. But if you want to dive into it, we can make a separate branch in this repository for gcp support.
